//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by res.rc
//
#define IDI_MAIN                        101
#define IDR_MAIN                        102
#define IDD_ABOUT                       103
#define IDD_SOUNDEDITOR                 106
#define IDD_SETABFM                     107
#define IDD_SETABPCM                    108
#define IDB_MAINTB                      112
#define IDD_PROGRESS                    113
#define IDR_EVENTITEM                   114
#define IDR_PIANOROLL                   116
#define IDB_LOGO                        117
#define IDC_TYPE                        1000
#define IDC_BM                          1001
#define IDC_BL                          1002
#define IDC_PE                          1002
#define IDC_PC                          1003
#define IDC_DAN                         1003
#define IDC_DSN                         1004
#define IDC_WID                         1004
#define IDC_TLFO                        1005
#define IDC_LFO                         1006
#define IDC_PAN                         1007
#define IDC_TPAN                        1008
#define IDC_ALG                         1009
#define IDC_TALG                        1010
#define IDC_OP                          1011
#define IDC_LP                          1011
#define IDC_EAM                         1012
#define IDC_EVB                         1013
#define IDC_XOF                         1014
#define IDC_SUS                         1015
#define IDC_KSR                         1016
#define IDC_RM                          1016
#define IDC_AR                          1017
#define IDC_VERSION                     1017
#define IDC_DR                          1018
#define IDC_SL                          1019
#define IDC_SR                          1020
#define IDC_PROGRESS                    1020
#define IDC_RR                          1021
#define IDC_MULTI                       1022
#define IDC_EP                          1022
#define IDC_SMW5VERSION                 1022
#define IDC_DT                          1023
#define IDC_HWVERSION                   1023
#define IDC_TL                          1024
#define IDC_TAR                         1025
#define IDC_TDR                         1026
#define IDC_TSL                         1027
#define IDC_TSR                         1028
#define IDC_TRR                         1029
#define IDC_TMULTI                      1030
#define IDC_TDT                         1031
#define IDC_TTL                         1032
#define IDC_KSL                         1034
#define IDC_TKSL                        1035
#define IDC_DAM                         1036
#define IDC_DVB                         1037
#define IDC_FB                          1038
#define IDC_WS                          1039
#define IDC_TDAM                        1040
#define IDC_TEAM                        1041
#define IDC_TFB                         1042
#define IDC_TWS                         1043
#define ID_EXIT                         40001
#define ID_OPENSMAF                     40002
#define ID_ABOUT                        40003
#define ID_HELPINDEX                    40004
#define ID_PLAY                         40005
#define ID_STOP                         40006
#define ID_CLOSE                        40007
#define ID_REWIND                       40010
#define ID_DETAILWND                    40011
#define ID_VTRACK1                      40013
#define ID_VTRACKALL                    40014
#define ID_VTRACK2                      40015
#define ID_VTRACK3                      40016
#define ID_VTRACK4                      40017
#define ID_VTRACK5                      40018
#define ID_VTRACK6                      40019
#define ID_VTRACK7                      40020
#define ID_VTRACK8                      40021
#define ID_VTRACK9                      40022
#define ID_VTRACK10                     40023
#define ID_VTRACK11                     40024
#define ID_VTRACK12                     40025
#define ID_VTRACK13                     40026
#define ID_VTRACK14                     40027
#define ID_VTRACK15                     40028
#define ID_VTRACK16                     40029
#define ID_MIDIPLAY                     40033
#define ID_MIDIRESET                    40035
#define ID_COMPILESMAF                  40036
#define ID_SAVESMAF                     40037
#define ID_NEWSMAF                      40038
#define ID_TOGGLENIAGARA                40039
#define ID_TOGGLERO                     40040
#define ID_CHECKCRC                     40041
#define ID_TOGGLENP                     40042
#define ID_EIINSERTAFTER                40043
#define ID_EIDELETE                     40045
#define ID_EIEDIT                       40046
#define ID_EIINSERTBEFORE               40047
#define ID_PRSCROLLTO                   40048
#define ID_PRDELETE                     40049
#define ID_PRONLYTRACK                  40050
#define ID_PRPLAYEMUHERE                40056
#define ID_RELOAD                       40057
#define ID_RECONVERT                    40058
#define ID_PRSETSTART                   40060
#define ID_PRSETSTOP                    40061
#define ID_EISETSTART                   40062
#define ID_EISETSTOP                    40063
#define ID_SAVESETTINGS                 40064
#define ID_PRPLAYMIDIHERE               40066

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40067
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
