#define FGBLACK		0
#define FGRED		FOREGROUND_RED
#define FGYELLOW	(FOREGROUND_RED | FOREGROUND_GREEN)
#define FGGREEN		FOREGROUND_GREEN
#define FGCYAN		(FOREGROUND_GREEN | FOREGROUND_BLUE)
#define FGBLUE		FOREGROUND_BLUE
#define FGPURPLE	(FOREGROUND_RED | FOREGROUND_BLUE)
#define FGWHITE		(FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE)
#define FGLIGHT		FOREGROUND_INTENSITY

#define BGBLACK		0
#define BGRED		BACKGROUND_RED
#define BGYELLOW	(BACKGROUND_RED | BACKGROUND_GREEN)
#define BGGREEN		BACKGROUND_GREEN
#define BGCYAN		(BACKGROUND_GREEN | BACKGROUND_BLUE)
#define BGBLUE		BACKGROUND_BLUE
#define BGPURPLE	(BACKGROUND_RED | BACKGROUND_BLUE)
#define BGWHITE		(BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE)
#define BGLIGHT		BACKGROUND_INTENSITY

int getone(void);
void putstr(LPCTSTR str);
void putstrf(LPCTSTR str, ...);
void setcolor(WORD flags);
int geteone(void);
