// PROLLWM
#define WM_PROLL				WM_USER

#define PROLLWM_SCROLLTO		0
#define PROLLWM_SETROLLWIDTH	1
#define PROLLWM_SETROLLHEIGHT	2
#define PROLLWM_SETVISIBLETRACK	3
#define PROLLWM_GETROLLWIDTH	4
#define PROLLWM_GETROLLHEIGHT	5
#define PROLLWM_GETVISIBLETRACK	6
#define PROLLWM_GETSCROLL		7
#define PROLLWM_SETSMAF			8
#define PROLLWM_SETCURRENTPOS	9
#define PROLLWM_SETOPTIONSTRING	10
#define PROLLWM_GETOPTIONSTRING	11
#define PROLLWM_SETREADONLY		12
#define PROLLWM_RELOADCONFIG	13
#define PROLLWM_SETHILIGHTEVENT	14
#define PROLLWM_SETNIAGARATOUCH	15
#define PROLLWM_GETNIAGARATOUCH	16
#define PROLLWM_GETREADONLY		17
#define PROLLWM_SETSHOWVISIBLEEVENTNUM	18
#define PROLLWM_GETSHOWVISIBLEEVENTNUM	19
#define PROLLWM_GETHILIGHTEVENT	20
#define PROLLWM_GETSCROLLMAG	21
#define PROLLWM_SETSCROLLMAG	22
#define PROLLWM_SETTEMPOGRIDSHIFT	23
#define PROLLWM_SETTEMPOGRIDEVERY	24

#define WM_PROLLNOTIFY			(WM_APP + 1)

#define PN_CURRENTPOSCHANGED	0
#define PN_CLICKED				1
#define PN_DBLCLICKED			2
#define PN_CONTEXTMENU			3
#define PN_RELEASED				4
#define PN_WHEELCLICKED			5
#define PN_EVENTCREATED			6
#define PN_EVENTDELETED			7	// non need?(It seems good when only PN_EVENTDELETING)
#define PN_EVENTMODIFIED		8
#define PN_EVENTHILIGHTED		9
#define PN_VTCHANGED			10
#define PN_EVENTMODIFYING		11
#define PN_EVENTDELETING		12
#define PN_EVENTCONTEXT			13

#define PNEM_MOVE				0
#define PNEM_SIZE				1

#define PRollGetScroll(hwnd) ((UINT)SendMessage(hwnd, WM_PROLL, PROLLWM_GETSCROLL, 0))

BOOL PRollInitialize(void);
